### ISSUE TITLE
AddFluentValidation breaks with MediatR 10

### ISSUE THREAD

**Issue by killergege** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#11]
Hello,

It seems that the update to MediatR 10 breaks this extension, probably because the contracts were moved to another assembly.
Is it possible to update the lib to handle this new version?

**Comment by MohammadRoshani** [comment]
I have same Problem. I forced downgrade to 9 version.

**Comment by GetoXs** [comment]
Thanks for reporting, this problem has been fixed in the new version https://www.nuget.org/packages/MediatR.Extensions.FluentValidation.AspNetCore/2.0.0
