### ISSUE TITLE
Does not work for IRequest (Mediatr 12)

### ISSUE THREAD

**Issue by balkarov** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#16]
**Describe the bug**
Validation does not work for `IRequest` (not generic)

**To Reproduce**
```c#
using MediatR;

public sealed class Command : IRequest
{
     public string Name { get; set; }
}

public sealed class CommandValidator : AbstractValidator<Command> {
     RuleFor(x => x.Name).NotEmpty();
}
```

Send mediatr request with this command and Name = null.

**Expected behavior**
 Validation does not work.

**Library (please complete the following information):**
 - Version 4.0.0

**Additional context**
You need change `IRequest<TResponse>` to `IBaseRequest` as like
```c#
public sealed class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : class, IBaseRequest
```

**Comment by GetoXs** [comment]
Resolved in new version https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore/releases/tag/5.0.0
