### ISSUE TITLE
The nuget is created in wrong way.

### ISSUE THREAD

**Issue by rafek1241** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#5]
```
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssemblies(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Collections.Generic.IEnumerable`1<Sy
stem.Reflection.Assembly>, Microsoft.Extensions.DependencyInjection.ServiceLifetime)'.
   at MediatR.Extensions.FluentValidation.AspNetCore.ServiceCollectionExtensions.AddFluentValidation(IServiceCollection services, IEnumerable`1 assemblies, ServiceLifetime lifetime)
```

When I copied code directly - it worked.

**Comment by GetoXs** [comment]
@rafek1241 
What version of FluentValidation do you use?

**Comment by rafek1241** [comment]
Latest. It doesn't matter. Just decompile the Nuget and you will see what's the matter. There's missing `using FluentValidation` within code

**Comment by GetoXs** [comment]
I have decompiled latest version (1.1.0) from nuget and there is `using FluentValidation`. Could you point out or describe step by step where is a problem?
![image](https://user-images.githubusercontent.com/6317670/90342941-868f7780-e00c-11ea-909d-65fbc14bde19.png)

**Comment by rafek1241** [comment]
@GetoXs I will respond this evening.

**Comment by rafek1241** [comment]
Okay, I'm using rider to develop applications.
Reproduction steps:
1. Open solution.
2. Include MediatR (add nuget to web project).
3. Include MediatR.Extensions.Microsoft.DependencyInjection
4. Include MediatR.Extensions.FluentValidation.AspNetCore. <-- this version won't have using that we want.
5. Include FluentValidation. Bah, your nuget's not working

**Comment by Vizzr** [comment]
I can confirm.
I am experiencing the same issue (Method not found).

All the packages are updated to their latest version.
Mediatr : 8.1.0
MediatR.Extensions.Microsoft.DependencyInjection : 8.1.0
MediatR.Extensions.FluentValidation.AspNetCore : 1.1.0
FluentValidation : 9.1.3

**Comment by Vizzr** [comment]
> I can confirm.
> I am experiencing the same issue (Method not found).
> 
> All the packages are updated to their latest version.
> Mediatr : 8.1.0
> MediatR.Extensions.Microsoft.DependencyInjection : 8.1.0
> MediatR.Extensions.FluentValidation.AspNetCore : 1.1.0
> FluentValidation : 9.1.3

Well, I looked at my Nuget packages and saw that I also had **FluentValidation.DependencyInjectionExtensions** installed.
Which is not necessary to be installed, since I am using this Nuget package.

Uninstalling **FluentValidation.DependencyInjectionExtensions** solved this issue for me.

**Comment by GetoXs** [comment]
Thanks guys, I find out than FluentValidation changes method fingerprint in version 9+ 
Here new fixed package https://www.nuget.org/packages/MediatR.Extensions.FluentValidation.AspNetCore/1.1.1
