### ISSUE TITLE
Update to fluentvalidation 9.3.0.preview 2 

### ISSUE THREAD

**Issue by alxtr1bal** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#6]
To be able to use .net 5 RC1

Is this Possible? 

Thanks

**Comment by GetoXs** [comment]
Yea, why not. Did you test it?

**Comment by GetoXs** [comment]
Good to hear that! 👍

**Comment by alxtr1bal** [comment]
Hi there 
So, can you update this to .net 5 ?

**Comment by GetoXs** [comment]
Is it necessary? There are any issues with .net 5?
Lower .net version give us better compatibility.
