### ISSUE TITLE
RuleForEach(x => x.items).SetValidator(new ItemValidator()) not validating

### ISSUE THREAD

**Issue by WijanRuiz** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#7]
Hi, first of all thank you for your work, that package is so usefull.

Now the problem.
I'm trying to validate a collection of DTOs with RuleForEach and setting a validator of another class with SetValidator and is not detecting the validation.

If I try to validate inside the Handler manually is working perfect.

**Comment by GetoXs** [comment]
@WijanRuiz is this case still a problem? You closed issue.
