### ISSUE TITLE
Solution version 1.1.1 is not compatible with FluentValidation 10.1.0 version

### ISSUE THREAD

**Issue by farshidnz** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#8]
MediatR.Extensions.FluentValidation.AspNetCoreversion version 1.1.1 is not compatible with FluentValidation 10.1.0 version.

Any chance to upgrade the packages within the solution?

**Comment by farshidnz** [comment]
@GetoXs Tagging you incase you haven't seen this.
Thanks

**Comment by GetoXs** [comment]
FluidValidation changed stamp of returned value from IList into List. In 10.x version.
https://github.com/FluentValidation/FluentValidation/commit/e77939ceac56ce5654f593e5d965f1b4c52c0262#diff-5d8897d13991d8145cab4dbb18c53d702c2d3084133a811033eb07654c65fadf

Fixed. New version available in nuget https://www.nuget.org/packages/MediatR.Extensions.FluentValidation.AspNetCore/1.2.0

Thanks for your patience

**Comment by farshidnz** [comment]
Awesome work. Thanks @GetoXs
